services:
  - type: web
    name: neurovision-api
    env: docker
    dockerfilePath: ./api/Dockerfile
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"

  - type: web
    name: neurovision-web
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    envVars:
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: neurovision-api
          envVarKey: RENDER_EXTERNAL_URL
